### ISSUE TITLE
This module does not handle multiple methods on the same URL

### ISSUE THREAD

**Issue by lght** [gwongz/flask-apiblueprint#1]
I can't register a

`POST /user`
`GET /user`

together, one of the two functions gets dropped because the internal mapping uses dictionary of rules, and not a dictionary of rules array.

**Comment by gwongz** [comment]
@lght Sorry about this - there is a fix in place that I'm hoping to deploy this weekend. Sorry for the delay!

**Comment by gwongz** [comment]
This has been fixed in the 1.0.0 release - sorry for the delay!
