### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by drorasaf** [gwongz/flask-apiblueprint#2]
Are there any plans for support in python3?
is it still maintained or should I fork?

**Comment by gwongz** [comment]
@drorasaf There aren't immediate plans for supporting python3 so forking might be the right way to go for now. Or feel free to submit a PR!

**Comment by drorasaf** [comment]
I am working on it, hope to finish this weekend.
I have another suggestion, create tox.ini or a travis.yaml to allow quick integration and check for all environments

**Comment by drorasaf** [comment]
#3

**Comment by gwongz** [comment]
Thanks @drorasaf. Just released version 1.0.0 which includes your merged PR as well as Travis.
